### ISSUE TITLE
Add Native Executor

### ISSUE THREAD

**Issue by foldedslipper** [NorskCracks/Roblox-Loader#1]
Hey really good job on this. Was wondering why nobody addressed anti-cheat head on like this instead of lazy work arounds. Do you have any plans on adding a native executor as well? Like instead of the loader staging a memory block for our own executor, just allocate enough for executor you write and that comes prepacked with .dll the .bat writes?

**Comment by NorskCracks** [comment]
A little beyond the scope of this project, but maybe in the future. :)
